dofile(minetest.get_modpath("setplaces").."/setwork.lua")
dofile(minetest.get_modpath("setplaces").."/setjobsite.lua")
dofile(minetest.get_modpath("setplaces").."/setmine.lua")
dofile(minetest.get_modpath("setplaces").."/setspouse.lua")
dofile(minetest.get_modpath("setplaces").."/setvacation.lua")
dofile(minetest.get_modpath("setplaces").."/setcoffee.lua")
dofile(minetest.get_modpath("setplaces").."/setbowl.lua")
